name: Create RFC Discussion

on:
  pull_request_target:
    types: [opened]
    paths:
      - 'rfcs/**.md'

jobs:
  create-discussion:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      discussions: write
    
    steps:
      - name: Get Changed Files
        id: changed-files
        uses: actions/github-script@v7
        with:
          script: |
            const { data: files } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            const mdFile = files.find(file => file.filename.startsWith('rfcs/') && file.filename.endsWith('.md'));
            if (!mdFile) {
              throw new Error('No markdown file found in rfcs directory');
            }
            core.setOutput('filename', mdFile.filename);

      - name: Create a new GitHub Discussion
        id: create-discussion
        uses: abirismyname/create-discussion@v1.x
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
        with:
          title: "RFC Discussion: ${{ github.event.pull_request.title }}"
          body: |
            This is the discussion thread for RFC PR #${{ github.event.pull_request.number }}.
            
            Please provide feedback and discuss the RFC here rather than in the PR comments.
            
            PR Link: ${{ github.event.pull_request.html_url }}
          repository-id: "R_kgDONaExcg"
          category-id: "DIC_kwDONaExcs4Cl4XD"

      - name: Update PR description
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prBody = context.payload.pull_request.body;
            const renderedUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/blob/${context.payload.pull_request.head.ref}/${process.env.MD_FILE}`;
            
            const updatedBody = prBody
              .replace('[Full Rendered Proposal]()', `[Full Rendered Proposal](${renderedUrl})`)
              .replace('[Discussion Thread]()', `[Discussion Thread](${process.env.DISCUSSION_URL})`);
            
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              body: updatedBody
            });
        env:
          DISCUSSION_URL: ${{ steps.create-discussion.outputs.discussion-url }}
          MD_FILE: ${{ steps.changed-files.outputs.filename }}